SELECT WFCON_Prompt, FDEF_Name, DEF_ID, FDEF_ID, WFCON_ID
FROM WFDefinitions INNER JOIN WFConfigurations ON DEF_ID = WFCON_DEFID JOIN WFFieldDefinitions ON FDEF_ID = WFCON_FDEFID
WHERE DEF_ID = 144
AND FDEF_Name NOT LIKE 'WFD_SubElems%'
AND FDEF_Name NOT LIKE 'SEL_System%'
AND FDEF_Name != 'WFD_Tab'
AND FDEF_Name != 'WFD_Group'
AND FDEF_Name != 'SEL_SQLGrid'
AND FDEF_Name != 'SEL_SQLRow'
ORDER BY WFCON_Prompt
